swagger: '2.0'
info:
  version: '1.0'
  title: TK-Challange
  description: 'TODO: Add Description'
  contact: {}
host: localhost
basePath: /api
securityDefinitions: {}
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /device:
    get:
      description: Gönderilen Bearer token üzerindeki cihazın bilgilerini döner
      summary: Show
      tags:
        - Device
      operationId: DeviceGet
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          default: Bearer {token}
          type: string
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Success2'
          examples:
            application/json:
              message:
              status: 200
              data:
                id: 1
                device_uuid: deneme-device-uuid
                language_code: tr
                region_code: TR
                platform: ios
                notification_tags: daily
                app_version: 1.0.1
                created_at: 2019-06-22 22:34:12
                updated_at: 2019-06-22 22:35:35
              errors:
          headers: {}
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
          examples:
            application/json:
              message: Unauthorized
              status: 401
              data:
              errors:
                - 'Authorization: Bearer is required'
    post:
      description: Device kayıt endpointi. Device ilk önce servis üzerinden kayıt edilir. Eğer device kayıtlı ise Get Access Token sekmesindeki endpoint çalıştırılarak access token edinilir.
      summary: Store
      tags:
        - Device
      operationId: DevicePost
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: device_uuid
          in: formData
          required: true
          type: string
          description: Device UUID
        - name: language_code
          in: formData
          required: true
          type: string
          description: 'Device Locale Code/ Ex: tr, en, fr'
        - name: region_code
          in: formData
          required: true
          type: string
          description: 'Device Region Code/ Ex: TR, EN, FR'
        - name: platform
          in: formData
          required: true
          type: string
          description: 'Platform/ Param: ios, android, other'
        - name: notification_token
          in: formData
          required: true
          type: string
          description: 'Notification Token/ Ex: onesignal player id'
        - name: notification_tags
          in: formData
          required: true
          type: string
          description: 'Notification Tags/ Ex: daily, weekly, monthly'
        - name: app_version
          in: formData
          required: true
          type: string
          description: 'Current App Version/ Ex: 1.0.1'
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/Success'
          examples:
            application/json:
              message: Device created.
              status: 201
              data:
                device_uuid: deneme-device-uuid
                language_code: tr
                region_code: TR
                platform: ios
                notification_tags: daily
                app_version: 1.0.1
                updated_at: 2019-06-22 22:34:12
                created_at: 2019-06-22 22:34:12
                id: 1
              errors:
          headers: {}
        422:
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/NoValidate'
          examples:
            application/json:
              message: The given data was invalid.
              data:
              status: 422
              errors:
                device_uuid:
                  - The device uuid field is required.
                language_code:
                  - The language code field is required.
                platform:
                  - The platform field is required.
                app_version:
                  - The app version field is required.
      security: []
    patch:
      description: Device bilgileri güncellemek için oluşturulmuş servis. Güncelleme başarılı olduysa 204 no content responsu döner.
      summary: Update
      tags:
        - Device
      operationId: DevicePatch
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: Authorization
          in: header
          required: false
          default: Bearer {token}
          type: string
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: language_code
          in: formData
          required: true
          type: string
          description: 'Device Locale Code/ Ex: tr, en, fr'
        - name: region_code
          in: formData
          required: true
          type: string
          description: 'Device Region Code/ Ex: TR, EN, FR'
        - name: platform
          in: formData
          required: true
          type: string
          description: 'Platform/ Param: ios, android, other'
        - name: notification_token
          in: formData
          required: true
          type: string
          description: 'Notification Token/ Ex: onesignal player id'
        - name: notification_tags
          in: formData
          required: true
          type: string
          description: 'Notification Tags/ Ex: daily, weekly, monthly'
        - name: app_version
          in: formData
          required: true
          type: string
          description: 'Current App Version/ Ex: 1.0.1'
      responses:
        204:
          description: ''
          schema:
            type: object
          headers: {}
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
          examples:
            application/json:
              message: Unauthorized
              status: 401
              data:
              errors:
                - 'Authorization: Bearer is required'
  /device/get-access-token:
    post:
      description: Access token her bu fonksiyon çalıştırıldığında yeniden oluşturulur. Bu endpoint uygulama her açıldığında tetiklenerek yeni bir token üretilmesi amacıyla yapılmıştır.
      summary: Get Access Token
      tags:
        - Device
      operationId: DeviceGetAccessTokenPost
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: device_token
          in: formData
          required: true
          type: string
          description: Device Unique Token
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Success1'
          examples:
            application/json:
              message:
              status: 200
              data:
                access_token: 2cyRKKil4pA1IBut11BO2xnokihmXAC5
              errors:
          headers: {}
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/DeviceIDNotFound'
          examples:
            application/json:
              message: Device ID Not Found
              status: 400
              data:
              errors:
      security: []
  /song/categories:
    get:
      description: Uygulamaya ait kategorilerin listesini döner.
      summary: Category List
      tags:
        - Song
      operationId: SongCategoriesGet
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          default: Bearer {token}
          type: string
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Success3'
          examples:
            application/json:
              message: Song category list
              status: 200
              data:
                - id: 1
                  thumbnail: https://lorempixel.com/400/400/?31876
                  created_at: 2019-06-22 22:25:31
                  updated_at: 2019-06-22 22:25:31
                  name: Aliquid ab et.
                - id: 2
                  thumbnail: https://lorempixel.com/400/400/?72059
                  created_at: 2019-06-22 22:25:31
                  updated_at: 2019-06-22 22:25:31
                  name: Non facere.
                - id: 3
                  thumbnail: https://lorempixel.com/400/400/?62620
                  created_at: 2019-06-22 22:25:31
                  updated_at: 2019-06-22 22:25:31
                  name: Quo minus.
                - id: 4
                  thumbnail: https://lorempixel.com/400/400/?31485
                  created_at: 2019-06-22 22:25:31
                  updated_at: 2019-06-22 22:25:31
                  name: Eos eos.
                - id: 5
                  thumbnail: https://lorempixel.com/400/400/?53636
                  created_at: 2019-06-22 22:25:31
                  updated_at: 2019-06-22 22:25:31
                  name: Ex et ipsum.
                - id: 6
                  thumbnail: https://lorempixel.com/400/400/?28956
                  created_at: 2019-06-22 22:25:31
                  updated_at: 2019-06-22 22:25:31
                  name: Quibusdam non.
                - id: 7
                  thumbnail: https://lorempixel.com/400/400/?38771
                  created_at: 2019-06-22 22:25:31
                  updated_at: 2019-06-22 22:25:31
                  name: Cupiditate.
                - id: 8
                  thumbnail: https://lorempixel.com/400/400/?27653
                  created_at: 2019-06-22 22:25:31
                  updated_at: 2019-06-22 22:25:31
                  name: Recusandae qui.
                - id: 9
                  thumbnail: https://lorempixel.com/400/400/?51075
                  created_at: 2019-06-22 22:25:31
                  updated_at: 2019-06-22 22:25:31
                  name: Vel facere.
                - id: 10
                  thumbnail: https://lorempixel.com/400/400/?47152
                  created_at: 2019-06-22 22:25:31
                  updated_at: 2019-06-22 22:25:31
                  name: Dolorum quasi.
              errors:
          headers: {}
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
          examples:
            application/json:
              message: Unauthorized
              status: 401
              data:
              errors:
                - 'Authorization: Bearer is required'
  /song/1/unfavorite:
    delete:
      description: Şarkıyı favorilerden kaldırır. Eğer sonuç başarılıysa 204 no-content gönderir.
      summary: Song Unfavorite
      tags:
        - Song
      operationId: Song1UnfavoriteDelete
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          default: Bearer {token}
          type: string
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
      responses:
        204:
          description: ''
          schema:
            type: object
          headers: {}
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
          examples:
            application/json:
              message: Unauthorized
              status: 401
              data:
              errors:
                - 'Authorization: Bearer is required'
  /song/1/favorite:
    post:
      description: Şarkıyı favorilere ekler.
      summary: Song Favorite
      tags:
        - Song
      operationId: Song1FavoritePost
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          default: Bearer {token}
          type: string
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/Success5'
          examples:
            application/json:
              message: Song favorite created
              status: 201
              data:
                song_id: 1
                device_id: 1
                updated_at: 2019-06-22 22:43:44
                created_at: 2019-06-22 22:43:44
                id: 1
              errors:
          headers: {}
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
          examples:
            application/json:
              message: Unauthorized
              status: 401
              data:
              errors:
                - 'Authorization: Bearer is required'
  /song/category/1:
    get:
      description: Kategorilere ait şarkıları döner
      summary: Song List
      tags:
        - Song
      operationId: SongCategory1Get
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: false
          default: Bearer {token}
          type: string
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Success4'
          examples:
            application/json:
              message:
              status: 200
              data:
                current_page: 1
                data:
                  - id: 1
                    category_id: 1
                    thumbnail: https://lorempixel.com/400/400/?69200
                    media: http://localhost/storage/media/song/nlL93BOMUKCxRQv.mp3
                    created_at: 2019-06-22 22:25:31
                    updated_at: 2019-06-22 22:25:31
                    has_favorite: false
                    name: Eum velit.
                  - id: 2
                    category_id: 1
                    thumbnail: https://lorempixel.com/400/400/?40530
                    media: http://localhost/storage/media/song/S2E4SRzAHbDvjQP.mp3
                    created_at: 2019-06-22 22:25:31
                    updated_at: 2019-06-22 22:25:31
                    has_favorite: false
                    name: Est nulla.
                  - id: 3
                    category_id: 1
                    thumbnail: https://lorempixel.com/400/400/?26302
                    media: http://localhost/storage/media/song/ANRoJpkjQPAwHKC.mp3
                    created_at: 2019-06-22 22:25:32
                    updated_at: 2019-06-22 22:25:32
                    has_favorite: false
                    name: Quos at.
                  - id: 4
                    category_id: 1
                    thumbnail: https://lorempixel.com/400/400/?24047
                    media: http://localhost/storage/media/song/ppvCBwCriab6oq3.mp3
                    created_at: 2019-06-22 22:25:32
                    updated_at: 2019-06-22 22:25:32
                    has_favorite: false
                    name: Quis et.
                  - id: 5
                    category_id: 1
                    thumbnail: https://lorempixel.com/400/400/?88467
                    media: http://localhost/storage/media/song/uih1q6271GSjJS9.mp3
                    created_at: 2019-06-22 22:25:32
                    updated_at: 2019-06-22 22:25:32
                    has_favorite: false
                    name: Eos quisquam.
                  - id: 6
                    category_id: 1
                    thumbnail: https://lorempixel.com/400/400/?81713
                    media: http://localhost/storage/media/song/RKkTcVMQFCFh8rM.mp3
                    created_at: 2019-06-22 22:25:32
                    updated_at: 2019-06-22 22:25:32
                    has_favorite: false
                    name: Nostrum labore.
                  - id: 7
                    category_id: 1
                    thumbnail: https://lorempixel.com/400/400/?61448
                    media: http://localhost/storage/media/song/iLvf13zcusE2nTE.mp3
                    created_at: 2019-06-22 22:25:32
                    updated_at: 2019-06-22 22:25:32
                    has_favorite: false
                    name: Ea.
                  - id: 8
                    category_id: 1
                    thumbnail: https://lorempixel.com/400/400/?79603
                    media: http://localhost/storage/media/song/l2ePucNerUvSTmP.mp3
                    created_at: 2019-06-22 22:25:32
                    updated_at: 2019-06-22 22:25:32
                    has_favorite: false
                    name: Natus.
                  - id: 9
                    category_id: 1
                    thumbnail: https://lorempixel.com/400/400/?23213
                    media: http://localhost/storage/media/song/v9W0rBO349e7Z9y.mp3
                    created_at: 2019-06-22 22:25:32
                    updated_at: 2019-06-22 22:25:32
                    has_favorite: false
                    name: Vel fugit.
                  - id: 10
                    category_id: 1
                    thumbnail: https://lorempixel.com/400/400/?43181
                    media: http://localhost/storage/media/song/2WlFILcC1zoaBS7.mp3
                    created_at: 2019-06-22 22:25:32
                    updated_at: 2019-06-22 22:25:32
                    has_favorite: false
                    name: Rerum.
                first_page_url: http://localhost/api/song/category/1?page=1
                from: 1
                last_page: 2
                last_page_url: http://localhost/api/song/category/1?page=2
                next_page_url: http://localhost/api/song/category/1?page=2
                path: http://localhost/api/song/category/1
                per_page: 10
                prev_page_url:
                to: 10
                total: 15
              errors:
          headers: {}
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Unauthorized'
          examples:
            application/json:
              message: Unauthorized
              status: 401
              data:
              errors:
                - 'Authorization: Bearer is required'
definitions:
  Success2:
    title: Success2
    example:
      message:
      status: 200
      data:
        id: 1
        device_uuid: deneme-device-uuid
        language_code: tr
        region_code: TR
        platform: ios
        notification_tags: daily
        app_version: 1.0.1
        created_at: 2019-06-22 22:34:12
        updated_at: 2019-06-22 22:35:35
      errors:
    type: object
    properties:
      message:
        type: string
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data'
      errors:
        type: string
    required:
      - status
      - data
  Success5:
    title: Success5
    example:
      message: Song favorite created
      status: 201
      data:
        song_id: 1
        device_id: 1
        updated_at: 2019-06-22 22:43:44
        created_at: 2019-06-22 22:43:44
        id: 1
      errors:
    type: object
    properties:
      message:
        type: string
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data6'
      errors:
        type: string
    required:
      - message
      - status
      - data
  Success3:
    title: Success3
    example:
      message: Song category list
      status: 200
      data:
        - id: 1
          thumbnail: https://lorempixel.com/400/400/?31876
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          name: Aliquid ab et.
        - id: 2
          thumbnail: https://lorempixel.com/400/400/?72059
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          name: Non facere.
        - id: 3
          thumbnail: https://lorempixel.com/400/400/?62620
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          name: Quo minus.
        - id: 4
          thumbnail: https://lorempixel.com/400/400/?31485
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          name: Eos eos.
        - id: 5
          thumbnail: https://lorempixel.com/400/400/?53636
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          name: Ex et ipsum.
        - id: 6
          thumbnail: https://lorempixel.com/400/400/?28956
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          name: Quibusdam non.
        - id: 7
          thumbnail: https://lorempixel.com/400/400/?38771
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          name: Cupiditate.
        - id: 8
          thumbnail: https://lorempixel.com/400/400/?27653
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          name: Recusandae qui.
        - id: 9
          thumbnail: https://lorempixel.com/400/400/?51075
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          name: Vel facere.
        - id: 10
          thumbnail: https://lorempixel.com/400/400/?47152
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          name: Dolorum quasi.
      errors:
    type: object
    properties:
      message:
        type: string
      status:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Data3'
      errors:
        type: string
    required:
      - message
      - status
      - data
  Data3:
    title: Data3
    example:
      id: 1
      thumbnail: https://lorempixel.com/400/400/?31876
      created_at: 2019-06-22 22:25:31
      updated_at: 2019-06-22 22:25:31
      name: Aliquid ab et.
    type: object
    properties:
      id:
        type: integer
        format: int32
      thumbnail:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
      name:
        type: string
    required:
      - id
      - thumbnail
      - created_at
      - updated_at
      - name
  Success1:
    title: Success1
    example:
      message:
      status: 200
      data:
        access_token: 2cyRKKil4pA1IBut11BO2xnokihmXAC5
      errors:
    type: object
    properties:
      message:
        type: string
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data1'
      errors:
        type: string
    required:
      - status
      - data
  Unauthorized:
    title: Unauthorized
    example:
      message: Unauthorized
      status: 401
      data:
      errors:
        - 'Authorization: Bearer is required'
    type: object
    properties:
      message:
        type: string
      status:
        type: integer
        format: int32
      data:
        type: string
      errors:
        type: array
        items:
          type: string
    required:
      - message
      - status
      - errors
  NoValidate:
    title: NoValidate
    example:
      message: The given data was invalid.
      data:
      status: 422
      errors:
        device_uuid:
          - The device uuid field is required.
        language_code:
          - The language code field is required.
        platform:
          - The platform field is required.
        app_version:
          - The app version field is required.
    type: object
    properties:
      message:
        type: string
      data:
        type: string
      status:
        type: integer
        format: int32
      errors:
        $ref: '#/definitions/Errors'
    required:
      - message
      - status
      - errors
  Errors:
    title: Errors
    example:
      device_uuid:
        - The device uuid field is required.
      language_code:
        - The language code field is required.
      platform:
        - The platform field is required.
      app_version:
        - The app version field is required.
    type: object
    properties:
      device_uuid:
        type: array
        items:
          type: string
      language_code:
        type: array
        items:
          type: string
      platform:
        type: array
        items:
          type: string
      app_version:
        type: array
        items:
          type: string
    required:
      - device_uuid
      - language_code
      - platform
      - app_version
  DeviceIDNotFound:
    title: DeviceIDNotFound
    example:
      message: Device ID Not Found
      status: 400
      data:
      errors:
    type: object
    properties:
      message:
        type: string
      status:
        type: integer
        format: int32
      data:
        type: string
      errors:
        type: string
    required:
      - message
      - status
  Data1:
    title: Data1
    example:
      access_token: 2cyRKKil4pA1IBut11BO2xnokihmXAC5
    type: object
    properties:
      access_token:
        type: string
    required:
      - access_token
  Success:
    title: Success
    example:
      message: Device created.
      status: 201
      data:
        device_uuid: deneme-device-uuid
        language_code: tr
        region_code: TR
        platform: ios
        notification_tags: daily
        app_version: 1.0.1
        updated_at: 2019-06-22 22:34:12
        created_at: 2019-06-22 22:34:12
        id: 1
      errors:
    type: object
    properties:
      message:
        type: string
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data'
      errors:
        type: string
    required:
      - message
      - status
      - data
  Data:
    title: Data
    example:
      device_uuid: deneme-device-uuid
      language_code: tr
      region_code: TR
      platform: ios
      notification_tags: daily
      app_version: 1.0.1
      updated_at: 2019-06-22 22:34:12
      created_at: 2019-06-22 22:34:12
      id: 1
    type: object
    properties:
      device_uuid:
        type: string
      language_code:
        type: string
      region_code:
        type: string
      platform:
        type: string
      notification_tags:
        type: string
      app_version:
        type: string
      updated_at:
        type: string
      created_at:
        type: string
      id:
        type: integer
        format: int32
    required:
      - device_uuid
      - language_code
      - region_code
      - platform
      - notification_tags
      - app_version
      - updated_at
      - created_at
      - id
  Success4:
    title: Success4
    example:
      message:
      status: 200
      data:
        current_page: 1
        data:
          - id: 1
            category_id: 1
            thumbnail: https://lorempixel.com/400/400/?69200
            media: http://localhost/storage/media/song/nlL93BOMUKCxRQv.mp3
            created_at: 2019-06-22 22:25:31
            updated_at: 2019-06-22 22:25:31
            has_favorite: false
            name: Eum velit.
          - id: 2
            category_id: 1
            thumbnail: https://lorempixel.com/400/400/?40530
            media: http://localhost/storage/media/song/S2E4SRzAHbDvjQP.mp3
            created_at: 2019-06-22 22:25:31
            updated_at: 2019-06-22 22:25:31
            has_favorite: false
            name: Est nulla.
          - id: 3
            category_id: 1
            thumbnail: https://lorempixel.com/400/400/?26302
            media: http://localhost/storage/media/song/ANRoJpkjQPAwHKC.mp3
            created_at: 2019-06-22 22:25:32
            updated_at: 2019-06-22 22:25:32
            has_favorite: false
            name: Quos at.
          - id: 4
            category_id: 1
            thumbnail: https://lorempixel.com/400/400/?24047
            media: http://localhost/storage/media/song/ppvCBwCriab6oq3.mp3
            created_at: 2019-06-22 22:25:32
            updated_at: 2019-06-22 22:25:32
            has_favorite: false
            name: Quis et.
          - id: 5
            category_id: 1
            thumbnail: https://lorempixel.com/400/400/?88467
            media: http://localhost/storage/media/song/uih1q6271GSjJS9.mp3
            created_at: 2019-06-22 22:25:32
            updated_at: 2019-06-22 22:25:32
            has_favorite: false
            name: Eos quisquam.
          - id: 6
            category_id: 1
            thumbnail: https://lorempixel.com/400/400/?81713
            media: http://localhost/storage/media/song/RKkTcVMQFCFh8rM.mp3
            created_at: 2019-06-22 22:25:32
            updated_at: 2019-06-22 22:25:32
            has_favorite: false
            name: Nostrum labore.
          - id: 7
            category_id: 1
            thumbnail: https://lorempixel.com/400/400/?61448
            media: http://localhost/storage/media/song/iLvf13zcusE2nTE.mp3
            created_at: 2019-06-22 22:25:32
            updated_at: 2019-06-22 22:25:32
            has_favorite: false
            name: Ea.
          - id: 8
            category_id: 1
            thumbnail: https://lorempixel.com/400/400/?79603
            media: http://localhost/storage/media/song/l2ePucNerUvSTmP.mp3
            created_at: 2019-06-22 22:25:32
            updated_at: 2019-06-22 22:25:32
            has_favorite: false
            name: Natus.
          - id: 9
            category_id: 1
            thumbnail: https://lorempixel.com/400/400/?23213
            media: http://localhost/storage/media/song/v9W0rBO349e7Z9y.mp3
            created_at: 2019-06-22 22:25:32
            updated_at: 2019-06-22 22:25:32
            has_favorite: false
            name: Vel fugit.
          - id: 10
            category_id: 1
            thumbnail: https://lorempixel.com/400/400/?43181
            media: http://localhost/storage/media/song/2WlFILcC1zoaBS7.mp3
            created_at: 2019-06-22 22:25:32
            updated_at: 2019-06-22 22:25:32
            has_favorite: false
            name: Rerum.
        first_page_url: http://localhost/api/song/category/1?page=1
        from: 1
        last_page: 2
        last_page_url: http://localhost/api/song/category/1?page=2
        next_page_url: http://localhost/api/song/category/1?page=2
        path: http://localhost/api/song/category/1
        per_page: 10
        prev_page_url:
        to: 10
        total: 15
      errors:
    type: object
    properties:
      message:
        type: string
      status:
        type: integer
        format: int32
      data:
        $ref: '#/definitions/Data4'
      errors:
        type: string
    required:
      - status
      - data
  Data4:
    title: Data4
    example:
      current_page: 1
      data:
        - id: 1
          category_id: 1
          thumbnail: https://lorempixel.com/400/400/?69200
          media: http://localhost/storage/media/song/nlL93BOMUKCxRQv.mp3
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          has_favorite: false
          name: Eum velit.
        - id: 2
          category_id: 1
          thumbnail: https://lorempixel.com/400/400/?40530
          media: http://localhost/storage/media/song/S2E4SRzAHbDvjQP.mp3
          created_at: 2019-06-22 22:25:31
          updated_at: 2019-06-22 22:25:31
          has_favorite: false
          name: Est nulla.
        - id: 3
          category_id: 1
          thumbnail: https://lorempixel.com/400/400/?26302
          media: http://localhost/storage/media/song/ANRoJpkjQPAwHKC.mp3
          created_at: 2019-06-22 22:25:32
          updated_at: 2019-06-22 22:25:32
          has_favorite: false
          name: Quos at.
        - id: 4
          category_id: 1
          thumbnail: https://lorempixel.com/400/400/?24047
          media: http://localhost/storage/media/song/ppvCBwCriab6oq3.mp3
          created_at: 2019-06-22 22:25:32
          updated_at: 2019-06-22 22:25:32
          has_favorite: false
          name: Quis et.
        - id: 5
          category_id: 1
          thumbnail: https://lorempixel.com/400/400/?88467
          media: http://localhost/storage/media/song/uih1q6271GSjJS9.mp3
          created_at: 2019-06-22 22:25:32
          updated_at: 2019-06-22 22:25:32
          has_favorite: false
          name: Eos quisquam.
        - id: 6
          category_id: 1
          thumbnail: https://lorempixel.com/400/400/?81713
          media: http://localhost/storage/media/song/RKkTcVMQFCFh8rM.mp3
          created_at: 2019-06-22 22:25:32
          updated_at: 2019-06-22 22:25:32
          has_favorite: false
          name: Nostrum labore.
        - id: 7
          category_id: 1
          thumbnail: https://lorempixel.com/400/400/?61448
          media: http://localhost/storage/media/song/iLvf13zcusE2nTE.mp3
          created_at: 2019-06-22 22:25:32
          updated_at: 2019-06-22 22:25:32
          has_favorite: false
          name: Ea.
        - id: 8
          category_id: 1
          thumbnail: https://lorempixel.com/400/400/?79603
          media: http://localhost/storage/media/song/l2ePucNerUvSTmP.mp3
          created_at: 2019-06-22 22:25:32
          updated_at: 2019-06-22 22:25:32
          has_favorite: false
          name: Natus.
        - id: 9
          category_id: 1
          thumbnail: https://lorempixel.com/400/400/?23213
          media: http://localhost/storage/media/song/v9W0rBO349e7Z9y.mp3
          created_at: 2019-06-22 22:25:32
          updated_at: 2019-06-22 22:25:32
          has_favorite: false
          name: Vel fugit.
        - id: 10
          category_id: 1
          thumbnail: https://lorempixel.com/400/400/?43181
          media: http://localhost/storage/media/song/2WlFILcC1zoaBS7.mp3
          created_at: 2019-06-22 22:25:32
          updated_at: 2019-06-22 22:25:32
          has_favorite: false
          name: Rerum.
      first_page_url: http://localhost/api/song/category/1?page=1
      from: 1
      last_page: 2
      last_page_url: http://localhost/api/song/category/1?page=2
      next_page_url: http://localhost/api/song/category/1?page=2
      path: http://localhost/api/song/category/1
      per_page: 10
      prev_page_url:
      to: 10
      total: 15
    type: object
    properties:
      current_page:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/Data5'
      first_page_url:
        type: string
      from:
        type: integer
        format: int32
      last_page:
        type: integer
        format: int32
      last_page_url:
        type: string
      next_page_url:
        type: string
      path:
        type: string
      per_page:
        type: integer
        format: int32
      prev_page_url:
        type: string
      to:
        type: integer
        format: int32
      total:
        type: integer
        format: int32
    required:
      - current_page
      - data
      - first_page_url
      - from
      - last_page
      - last_page_url
      - next_page_url
      - path
      - per_page
      - to
      - total
  Data5:
    title: Data5
    example:
      id: 1
      category_id: 1
      thumbnail: https://lorempixel.com/400/400/?69200
      media: http://localhost/storage/media/song/nlL93BOMUKCxRQv.mp3
      created_at: 2019-06-22 22:25:31
      updated_at: 2019-06-22 22:25:31
      has_favorite: false
      name: Eum velit.
    type: object
    properties:
      id:
        type: integer
        format: int32
      category_id:
        type: integer
        format: int32
      thumbnail:
        type: string
      media:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
      has_favorite:
        type: boolean
      name:
        type: string
    required:
      - id
      - category_id
      - thumbnail
      - media
      - created_at
      - updated_at
      - has_favorite
      - name
  Data6:
    title: Data6
    example:
      song_id: 1
      device_id: 1
      updated_at: 2019-06-22 22:43:44
      created_at: 2019-06-22 22:43:44
      id: 1
    type: object
    properties:
      song_id:
        type: string
      device_id:
        type: integer
        format: int32
      updated_at:
        type: string
      created_at:
        type: string
      id:
        type: integer
        format: int32
    required:
      - song_id
      - device_id
      - updated_at
      - created_at
      - id
tags:
  - name: Device
  - name: Song